# Generated by Django 3.0.5 on 2020-05-04 21:24

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 21, 24, 8, 616665, tzinfo=datetime.timezone.utc)),
        ),
    ]
