# Generated by Django 3.0.5 on 2020-05-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(upload_to='movies'),
        ),
    ]
