# Generated by Django 3.0.5 on 2020-05-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20200508_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(upload_to='clip'),
        ),
    ]
