# Generated by Django 3.0.5 on 2020-05-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20200508_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_trailer',
        ),
    ]
