# Generated by Django 5.2 on 2025-06-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0013_remove_movie_movie_trailer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["-created"],
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
        migrations.AlterModelOptions(
            name="movielinks",
            options={
                "verbose_name": "Movie Link",
                "verbose_name_plural": "Movie Links",
            },
        ),
        migrations.AlterField(
            model_name="movie",
            name="banner",
            field=models.ImageField(upload_to="movies_banner/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="cast",
            field=models.CharField(
                help_text="Comma-separated actor names", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("drama", "Drama"),
                    ("comedy", "Comedy"),
                    ("romance", "Romance"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(upload_to="movies/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.CharField(
                choices=[("english", "English"), ("german", "German")], max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("RA", "Recently Added"),
                    ("MW", "Most Watched"),
                    ("TR", "Top Rated"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year_of_production",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="movielinks",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="movielinks",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_watch_links",
                to="movie.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movielinks",
            name="type",
            field=models.CharField(
                choices=[("D", "Download Link"), ("W", "Watch Link")], max_length=1
            ),
        ),
    ]
