# Generated by Django 5.2 on 2025-06-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0015_movie_rating_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
        migrations.AlterModelOptions(
            name="movielinks",
            options={},
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
        migrations.AlterField(
            model_name="movie",
            name="cast",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
