# Generated by Django 5.2 on 2025-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0016_alter_movie_options_alter_movielinks_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(
                default=90, help_text="Duration in minutes"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="cast",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, to="movie.genre"),
        ),
    ]
